package AppliChat;


/**
* AppliChat/ChatPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Talk.idl
* Wednesday, October 23, 2019 3:09:02 PM CEST
*/

public abstract class ChatPOA extends org.omg.PortableServer.Servant
 implements AppliChat.ChatOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("inscription", new java.lang.Integer (0));
    _methods.put ("diffusionMsg", new java.lang.Integer (1));
    _methods.put ("disconnect", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // AppliChat/Chat/inscription
       {
         AppliChat.Talk ior = AppliChat.TalkHelper.read (in);
         this.inscription (ior);
         out = $rh.createReply();
         break;
       }


  // enregistre les IOR
       case 1:  // AppliChat/Chat/diffusionMsg
       {
         String name = in.read_string ();
         String msg = in.read_string ();
         this.diffusionMsg (name, msg);
         out = $rh.createReply();
         break;
       }


  // parcours et envoi les IOR
       case 2:  // AppliChat/Chat/disconnect
       {
         AppliChat.Talk user = AppliChat.TalkHelper.read (in);
         this.disconnect (user);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:AppliChat/Chat:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Chat _this() 
  {
    return ChatHelper.narrow(
    super._this_object());
  }

  public Chat _this(org.omg.CORBA.ORB orb) 
  {
    return ChatHelper.narrow(
    super._this_object(orb));
  }


} // class ChatPOA
