package AppliChat;


/**
* AppliChat/ChatOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Talk.idl
* Wednesday, October 23, 2019 3:09:02 PM CEST
*/

public interface ChatOperations 
{
  void inscription (AppliChat.Talk ior);

  // enregistre les IOR
  void diffusionMsg (String name, String msg);

  // parcours et envoi les IOR
  void disconnect (AppliChat.Talk user);
} // interface ChatOperations
