package AppliChat;


/**
* AppliChat/TalkOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Talk.idl
* Wednesday, October 23, 2019 3:09:02 PM CEST
*/

public interface TalkOperations 
{
  String name ();
  void name (String newName);
  void sendMsg (String name, String msg);
} // interface TalkOperations
