package AppliChat;


/**
* AppliChat/Talk.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Talk.idl
* Monday, October 21, 2019 4:56:50 PM CEST
*/

public interface Talk extends TalkOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Talk
