package AppliChat;

/**
* AppliChat/TalkHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Talk.idl
* Monday, October 21, 2019 4:56:49 PM CEST
*/

public final class TalkHolder implements org.omg.CORBA.portable.Streamable
{
  public AppliChat.Talk value = null;

  public TalkHolder ()
  {
  }

  public TalkHolder (AppliChat.Talk initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AppliChat.TalkHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AppliChat.TalkHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AppliChat.TalkHelper.type ();
  }

}
