package AppliChat;


/**
* AppliChat/TalkPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Talk.idl
* Monday, October 21, 2019 4:56:49 PM CEST
*/

public abstract class TalkPOA extends org.omg.PortableServer.Servant
 implements AppliChat.TalkOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_msg", new java.lang.Integer (0));
    _methods.put ("_set_msg", new java.lang.Integer (1));
    _methods.put ("_get_name", new java.lang.Integer (2));
    _methods.put ("_set_name", new java.lang.Integer (3));
    _methods.put ("sendMsg", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // AppliChat/Talk/_get_msg
       {
         String $result = null;
         $result = this.msg ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // AppliChat/Talk/_set_msg
       {
         String newMsg = in.read_string ();
         this.msg (newMsg);
         out = $rh.createReply();
         break;
       }

       case 2:  // AppliChat/Talk/_get_name
       {
         String $result = null;
         $result = this.name ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // AppliChat/Talk/_set_name
       {
         String newName = in.read_string ();
         this.name (newName);
         out = $rh.createReply();
         break;
       }

       case 4:  // AppliChat/Talk/sendMsg
       {
         String msg = in.read_string ();
         this.sendMsg (msg);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:AppliChat/Talk:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Talk _this() 
  {
    return TalkHelper.narrow(
    super._this_object());
  }

  public Talk _this(org.omg.CORBA.ORB orb) 
  {
    return TalkHelper.narrow(
    super._this_object(orb));
  }


} // class TalkPOA
