package AppliChat;


/**
* AppliChat/TalkOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Talk.idl
* Monday, October 21, 2019 4:56:50 PM CEST
*/

public interface TalkOperations 
{
  String msg ();
  void msg (String newMsg);
  String name ();
  void name (String newName);
  void sendMsg (String msg);
} // interface TalkOperations
